import { Toaster } from "react-hot-toast";
import ClientOnly from "./components/ClientOnly";
import AuthForm from "./components/modals/AuthForm";
import Navbar from "./components/navbar/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "./components/Footer";
import CartDrawer from "./components/cart/CartDrawer";
import NotificationProvider from "./components/NotificationProvider";
import { Suspense } from "react";
import Loading from "./loading";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className="min-h-screen">
                    <ClientOnly>
                        <Toaster />
                        <Navbar />
                        <CartDrawer />
                        <AuthForm />
                        <NotificationProvider />
                    </ClientOnly>
                    {/* <Suspense fallback={<Loading />}>{children}</Suspense> */}
                    <>{children}</>
                </div>
                <Footer />
            </body>
        </html>
    );
}
